server:
  port: 8090
#使用freemarker的配置
spring:
  mvc:
    view:
      #文件位置 不能修改
      prefix: /templates
      #文件后缀
      suffix: .ftl
  freemarker:
    suffix:  .ftl
  #消息表达式用到的properties文件所在位置
  messages:
    basename: message
